apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80

#kubectl create -f pod.yaml
#kubectl edit pod pod.yaml
#kubectl desribe pod podname
