apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: cont-1
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"

